// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { adminCancelAdminFlightData, adminCancelAdminFlightErrors, adminCancelAdminFlightResponses, adminCreateFlightData, adminCreateFlightErrors, adminCreateFlightResponses, adminDeleteFlightData, adminDeleteFlightErrors, adminDeleteFlightResponses, adminGetAdminFlightData, adminGetAdminFlightErrors, adminGetAdminFlightResponses, adminGetStatsData, adminGetStatsResponses, adminListBookingsData, adminListBookingsErrors, adminListBookingsResponses, adminListFlightsData, adminListFlightsErrors, adminListFlightsResponses, adminUpdateBookingStatusData, adminUpdateBookingStatusErrors, adminUpdateBookingStatusResponses, adminUpdateFlightData, adminUpdateFlightErrors, adminUpdateFlightResponses, airportsListAirportsData, airportsListAirportsErrors, airportsListAirportsResponses, bookingsCancelPublicBookingData, bookingsCancelPublicBookingErrors, bookingsCancelPublicBookingResponses, bookingsCreateBookingData, bookingsCreateBookingErrors, bookingsCreateBookingResponses, bookingsLookupBookingData, bookingsLookupBookingErrors, bookingsLookupBookingResponses, flightsGetFlightData, flightsGetFlightErrors, flightsGetFlightResponses, flightsSearchFlightsData, flightsSearchFlightsErrors, flightsSearchFlightsResponses, loginLoginAccessTokenData, loginLoginAccessTokenErrors, loginLoginAccessTokenResponses, loginTestTokenData, loginTestTokenResponses, usersReadUserMeData, usersReadUserMeResponses, usersUpdatePasswordMeData, usersUpdatePasswordMeErrors, usersUpdatePasswordMeResponses, utilsHealthCheckData, utilsHealthCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class LoginService {
    /**
     * Login Access Token
     */
    public static loginAccessToken<ThrowOnError extends boolean = true>(options: Options<loginLoginAccessTokenData, ThrowOnError>) {
        return (options.client ?? client).post<loginLoginAccessTokenResponses, loginLoginAccessTokenErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/api/v1/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }

    /**
     * Test Token
     */
    public static testToken<ThrowOnError extends boolean = true>(options?: Options<loginTestTokenData, ThrowOnError>) {
        return (options?.client ?? client).post<loginTestTokenResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/login/test-token',
            ...options
        });
    }
}

export class UsersService {
    /**
     * Read User Me
     */
    public static readUserMe<ThrowOnError extends boolean = true>(options?: Options<usersReadUserMeData, ThrowOnError>) {
        return (options?.client ?? client).get<usersReadUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me',
            ...options
        });
    }

    /**
     * Update Password Me
     */
    public static updatePasswordMe<ThrowOnError extends boolean = true>(options: Options<usersUpdatePasswordMeData, ThrowOnError>) {
        return (options.client ?? client).patch<usersUpdatePasswordMeResponses, usersUpdatePasswordMeErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/users/me/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     */
    public static healthCheck<ThrowOnError extends boolean = true>(options?: Options<utilsHealthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<utilsHealthCheckResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/utils/health-check/',
            ...options
        });
    }
}

export class AirportsService {
    /**
     * List Airports
     */
    public static listAirports<ThrowOnError extends boolean = true>(options?: Options<airportsListAirportsData, ThrowOnError>) {
        return (options?.client ?? client).get<airportsListAirportsResponses, airportsListAirportsErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/airports',
            ...options
        });
    }
}

export class FlightsService {
    /**
     * Search Flights
     */
    public static searchFlights<ThrowOnError extends boolean = true>(options: Options<flightsSearchFlightsData, ThrowOnError>) {
        return (options.client ?? client).get<flightsSearchFlightsResponses, flightsSearchFlightsErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/flights/search',
            ...options
        });
    }

    /**
     * Get Flight
     */
    public static getFlight<ThrowOnError extends boolean = true>(options: Options<flightsGetFlightData, ThrowOnError>) {
        return (options.client ?? client).get<flightsGetFlightResponses, flightsGetFlightErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/flights/{flight_id}',
            ...options
        });
    }
}

export class BookingsService {
    /**
     * Create Booking
     */
    public static createBooking<ThrowOnError extends boolean = true>(options: Options<bookingsCreateBookingData, ThrowOnError>) {
        return (options.client ?? client).post<bookingsCreateBookingResponses, bookingsCreateBookingErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/bookings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Lookup Booking
     */
    public static lookupBooking<ThrowOnError extends boolean = true>(options: Options<bookingsLookupBookingData, ThrowOnError>) {
        return (options.client ?? client).post<bookingsLookupBookingResponses, bookingsLookupBookingErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/bookings/lookup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Cancel Public Booking
     */
    public static cancelPublicBooking<ThrowOnError extends boolean = true>(options: Options<bookingsCancelPublicBookingData, ThrowOnError>) {
        return (options.client ?? client).post<bookingsCancelPublicBookingResponses, bookingsCancelPublicBookingErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/bookings/cancel',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class AdminService {
    /**
     * Get Stats
     */
    public static getStats<ThrowOnError extends boolean = true>(options?: Options<adminGetStatsData, ThrowOnError>) {
        return (options?.client ?? client).get<adminGetStatsResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/stats',
            ...options
        });
    }

    /**
     * List Flights
     */
    public static listFlights<ThrowOnError extends boolean = true>(options?: Options<adminListFlightsData, ThrowOnError>) {
        return (options?.client ?? client).get<adminListFlightsResponses, adminListFlightsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/flights',
            ...options
        });
    }

    /**
     * Create Flight
     */
    public static createFlight<ThrowOnError extends boolean = true>(options: Options<adminCreateFlightData, ThrowOnError>) {
        return (options.client ?? client).post<adminCreateFlightResponses, adminCreateFlightErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/flights',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Delete Flight
     */
    public static deleteFlight<ThrowOnError extends boolean = true>(options: Options<adminDeleteFlightData, ThrowOnError>) {
        return (options.client ?? client).delete<adminDeleteFlightResponses, adminDeleteFlightErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/flights/{flight_id}',
            ...options
        });
    }

    /**
     * Get Admin Flight
     */
    public static getAdminFlight<ThrowOnError extends boolean = true>(options: Options<adminGetAdminFlightData, ThrowOnError>) {
        return (options.client ?? client).get<adminGetAdminFlightResponses, adminGetAdminFlightErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/flights/{flight_id}',
            ...options
        });
    }

    /**
     * Update Flight
     */
    public static updateFlight<ThrowOnError extends boolean = true>(options: Options<adminUpdateFlightData, ThrowOnError>) {
        return (options.client ?? client).patch<adminUpdateFlightResponses, adminUpdateFlightErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/flights/{flight_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }

    /**
     * Cancel Admin Flight
     */
    public static cancelAdminFlight<ThrowOnError extends boolean = true>(options: Options<adminCancelAdminFlightData, ThrowOnError>) {
        return (options.client ?? client).post<adminCancelAdminFlightResponses, adminCancelAdminFlightErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/flights/{flight_id}/cancel',
            ...options
        });
    }

    /**
     * List Bookings
     */
    public static listBookings<ThrowOnError extends boolean = true>(options?: Options<adminListBookingsData, ThrowOnError>) {
        return (options?.client ?? client).get<adminListBookingsResponses, adminListBookingsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/bookings',
            ...options
        });
    }

    /**
     * Update Booking Status
     */
    public static updateBookingStatus<ThrowOnError extends boolean = true>(options: Options<adminUpdateBookingStatusData, ThrowOnError>) {
        return (options.client ?? client).patch<adminUpdateBookingStatusResponses, adminUpdateBookingStatusErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/v1/admin/bookings/{booking_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
