// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AdminStats
 */
export type AdminStats = {
    /**
     * Scheduled Future Flights
     */
    scheduled_future_flights: number;
    /**
     * Confirmed Bookings
     */
    confirmed_bookings: number;
    /**
     * Seats Sold
     */
    seats_sold: number;
    /**
     * Seats Available
     */
    seats_available: number;
    /**
     * Load Factor
     */
    load_factor: number;
};

/**
 * AirportPublic
 */
export type AirportPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * City
     */
    city: string;
    /**
     * Country
     */
    country: string;
    /**
     * Name
     */
    name: string;
    /**
     * Timezone
     */
    timezone: string;
};

/**
 * AirportsPublic
 */
export type AirportsPublic = {
    /**
     * Data
     */
    data: Array<AirportPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BookingCreate
 */
export type BookingCreate = {
    /**
     * Flight Id
     */
    flight_id: string;
    /**
     * Passenger Name
     */
    passenger_name: string;
    /**
     * Passenger Email
     */
    passenger_email: string;
};

/**
 * BookingLookup
 */
export type BookingLookup = {
    /**
     * Booking Reference
     */
    booking_reference: string;
    /**
     * Passenger Email
     */
    passenger_email: string;
};

/**
 * BookingPublic
 */
export type BookingPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Booking Reference
     */
    booking_reference: string;
    flight: FlightPublic;
    /**
     * Passenger Name
     */
    passenger_name: string;
    /**
     * Passenger Email
     */
    passenger_email: string;
    status: BookingStatus;
    /**
     * Booked Price Cents
     */
    booked_price_cents: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * BookingStatus
 */
export type BookingStatus = 'confirmed' | 'cancelled';

/**
 * BookingUpdate
 */
export type BookingUpdate = {
    status: BookingStatus;
};

/**
 * BookingsPublic
 */
export type BookingsPublic = {
    /**
     * Data
     */
    data: Array<BookingPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EffectiveFlightStatus
 */
export type EffectiveFlightStatus = 'scheduled' | 'cancelled' | 'departed';

/**
 * FlightCreate
 */
export type FlightCreate = {
    /**
     * Flight Number
     */
    flight_number: string;
    /**
     * Origin Id
     */
    origin_id: string;
    /**
     * Destination Id
     */
    destination_id: string;
    /**
     * Departure At
     */
    departure_at: string;
    /**
     * Arrival At
     */
    arrival_at: string;
    /**
     * Price Cents
     */
    price_cents: number;
    /**
     * Total Capacity
     */
    total_capacity: number;
};

/**
 * FlightPublic
 */
export type FlightPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Flight Number
     */
    flight_number: string;
    origin: AirportPublic;
    destination: AirportPublic;
    /**
     * Departure At
     */
    departure_at: string;
    /**
     * Arrival At
     */
    arrival_at: string;
    /**
     * Price Cents
     */
    price_cents: number;
    /**
     * Currency
     */
    currency: string;
    /**
     * Total Capacity
     */
    total_capacity: number;
    /**
     * Available Capacity
     */
    available_capacity: number;
    status: FlightStatus;
    effective_status: EffectiveFlightStatus;
};

/**
 * FlightStatus
 */
export type FlightStatus = 'scheduled' | 'cancelled';

/**
 * FlightUpdate
 */
export type FlightUpdate = {
    /**
     * Flight Number
     */
    flight_number?: string | null;
    /**
     * Origin Id
     */
    origin_id?: string | null;
    /**
     * Destination Id
     */
    destination_id?: string | null;
    /**
     * Departure At
     */
    departure_at?: string | null;
    /**
     * Arrival At
     */
    arrival_at?: string | null;
    /**
     * Price Cents
     */
    price_cents?: number | null;
    /**
     * Total Capacity
     */
    total_capacity?: number | null;
    status?: FlightStatus | null;
};

/**
 * FlightsPublic
 */
export type FlightsPublic = {
    /**
     * Data
     */
    data: Array<FlightPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type airportsListAirportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/airports';
};

export type airportsListAirportsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type airportsListAirportsError = airportsListAirportsErrors[keyof airportsListAirportsErrors];

export type airportsListAirportsResponses = {
    /**
     * Successful Response
     */
    200: AirportsPublic;
};

export type airportsListAirportsResponse = airportsListAirportsResponses[keyof airportsListAirportsResponses];

export type flightsSearchFlightsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Origin
         */
        origin: string;
        /**
         * Destination
         */
        destination: string;
        /**
         * Departure Date
         */
        departure_date: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/flights/search';
};

export type flightsSearchFlightsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type flightsSearchFlightsError = flightsSearchFlightsErrors[keyof flightsSearchFlightsErrors];

export type flightsSearchFlightsResponses = {
    /**
     * Successful Response
     */
    200: FlightsPublic;
};

export type flightsSearchFlightsResponse = flightsSearchFlightsResponses[keyof flightsSearchFlightsResponses];

export type flightsGetFlightData = {
    body?: never;
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/api/v1/flights/{flight_id}';
};

export type flightsGetFlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type flightsGetFlightError = flightsGetFlightErrors[keyof flightsGetFlightErrors];

export type flightsGetFlightResponses = {
    /**
     * Successful Response
     */
    200: FlightPublic;
};

export type flightsGetFlightResponse = flightsGetFlightResponses[keyof flightsGetFlightResponses];

export type bookingsCreateBookingData = {
    body: BookingCreate;
    path?: never;
    query?: never;
    url: '/api/v1/bookings';
};

export type bookingsCreateBookingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bookingsCreateBookingError = bookingsCreateBookingErrors[keyof bookingsCreateBookingErrors];

export type bookingsCreateBookingResponses = {
    /**
     * Successful Response
     */
    201: BookingPublic;
};

export type bookingsCreateBookingResponse = bookingsCreateBookingResponses[keyof bookingsCreateBookingResponses];

export type bookingsLookupBookingData = {
    body: BookingLookup;
    path?: never;
    query?: never;
    url: '/api/v1/bookings/lookup';
};

export type bookingsLookupBookingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bookingsLookupBookingError = bookingsLookupBookingErrors[keyof bookingsLookupBookingErrors];

export type bookingsLookupBookingResponses = {
    /**
     * Successful Response
     */
    200: BookingPublic;
};

export type bookingsLookupBookingResponse = bookingsLookupBookingResponses[keyof bookingsLookupBookingResponses];

export type bookingsCancelPublicBookingData = {
    body: BookingLookup;
    path?: never;
    query?: never;
    url: '/api/v1/bookings/cancel';
};

export type bookingsCancelPublicBookingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type bookingsCancelPublicBookingError = bookingsCancelPublicBookingErrors[keyof bookingsCancelPublicBookingErrors];

export type bookingsCancelPublicBookingResponses = {
    /**
     * Successful Response
     */
    200: BookingPublic;
};

export type bookingsCancelPublicBookingResponse = bookingsCancelPublicBookingResponses[keyof bookingsCancelPublicBookingResponses];

export type adminGetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/stats';
};

export type adminGetStatsResponses = {
    /**
     * Successful Response
     */
    200: AdminStats;
};

export type adminGetStatsResponse = adminGetStatsResponses[keyof adminGetStatsResponses];

export type adminListFlightsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/flights';
};

export type adminListFlightsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminListFlightsError = adminListFlightsErrors[keyof adminListFlightsErrors];

export type adminListFlightsResponses = {
    /**
     * Successful Response
     */
    200: FlightsPublic;
};

export type adminListFlightsResponse = adminListFlightsResponses[keyof adminListFlightsResponses];

export type adminCreateFlightData = {
    body: FlightCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/flights';
};

export type adminCreateFlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCreateFlightError = adminCreateFlightErrors[keyof adminCreateFlightErrors];

export type adminCreateFlightResponses = {
    /**
     * Successful Response
     */
    201: FlightPublic;
};

export type adminCreateFlightResponse = adminCreateFlightResponses[keyof adminCreateFlightResponses];

export type adminDeleteFlightData = {
    body?: never;
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/api/v1/admin/flights/{flight_id}';
};

export type adminDeleteFlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminDeleteFlightError = adminDeleteFlightErrors[keyof adminDeleteFlightErrors];

export type adminDeleteFlightResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminDeleteFlightResponse = adminDeleteFlightResponses[keyof adminDeleteFlightResponses];

export type adminGetAdminFlightData = {
    body?: never;
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/api/v1/admin/flights/{flight_id}';
};

export type adminGetAdminFlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminGetAdminFlightError = adminGetAdminFlightErrors[keyof adminGetAdminFlightErrors];

export type adminGetAdminFlightResponses = {
    /**
     * Successful Response
     */
    200: FlightPublic;
};

export type adminGetAdminFlightResponse = adminGetAdminFlightResponses[keyof adminGetAdminFlightResponses];

export type adminUpdateFlightData = {
    body: FlightUpdate;
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/api/v1/admin/flights/{flight_id}';
};

export type adminUpdateFlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateFlightError = adminUpdateFlightErrors[keyof adminUpdateFlightErrors];

export type adminUpdateFlightResponses = {
    /**
     * Successful Response
     */
    200: FlightPublic;
};

export type adminUpdateFlightResponse = adminUpdateFlightResponses[keyof adminUpdateFlightResponses];

export type adminCancelAdminFlightData = {
    body?: never;
    path: {
        /**
         * Flight Id
         */
        flight_id: string;
    };
    query?: never;
    url: '/api/v1/admin/flights/{flight_id}/cancel';
};

export type adminCancelAdminFlightErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCancelAdminFlightError = adminCancelAdminFlightErrors[keyof adminCancelAdminFlightErrors];

export type adminCancelAdminFlightResponses = {
    /**
     * Successful Response
     */
    200: FlightPublic;
};

export type adminCancelAdminFlightResponse = adminCancelAdminFlightResponses[keyof adminCancelAdminFlightResponses];

export type adminListBookingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: BookingStatus | null;
    };
    url: '/api/v1/admin/bookings';
};

export type adminListBookingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminListBookingsError = adminListBookingsErrors[keyof adminListBookingsErrors];

export type adminListBookingsResponses = {
    /**
     * Successful Response
     */
    200: BookingsPublic;
};

export type adminListBookingsResponse = adminListBookingsResponses[keyof adminListBookingsResponses];

export type adminUpdateBookingStatusData = {
    body: BookingUpdate;
    path: {
        /**
         * Booking Id
         */
        booking_id: string;
    };
    query?: never;
    url: '/api/v1/admin/bookings/{booking_id}';
};

export type adminUpdateBookingStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateBookingStatusError = adminUpdateBookingStatusErrors[keyof adminUpdateBookingStatusErrors];

export type adminUpdateBookingStatusResponses = {
    /**
     * Successful Response
     */
    200: BookingPublic;
};

export type adminUpdateBookingStatusResponse = adminUpdateBookingStatusResponses[keyof adminUpdateBookingStatusResponses];
