/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicManageRouteImport } from './routes/_public/manage'
import { Route as PublicFlightsIndexRouteImport } from './routes/_public/flights.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as PublicFlightsFlightIdRouteImport } from './routes/_public/flights.$flightId'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin/admin.bookings'
import { Route as AdminAdminFlightsIndexRouteImport } from './routes/_admin/admin.flights.index'
import { Route as AdminAdminFlightsNewRouteImport } from './routes/_admin/admin.flights.new'
import { Route as AdminAdminFlightsFlightIdEditRouteImport } from './routes/_admin/admin.flights.$flightId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicManageRoute = PublicManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFlightsIndexRoute = PublicFlightsIndexRouteImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicFlightsFlightIdRoute = PublicFlightsFlightIdRouteImport.update({
  id: '/flights/$flightId',
  path: '/flights/$flightId',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFlightsIndexRoute = AdminAdminFlightsIndexRouteImport.update({
  id: '/admin/flights/',
  path: '/admin/flights/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFlightsNewRoute = AdminAdminFlightsNewRouteImport.update({
  id: '/admin/flights/new',
  path: '/admin/flights/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFlightsFlightIdEditRoute =
  AdminAdminFlightsFlightIdEditRouteImport.update({
    id: '/admin/flights/$flightId/edit',
    path: '/admin/flights/$flightId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/manage': typeof PublicManageRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/flights/$flightId': typeof PublicFlightsFlightIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/flights/': typeof PublicFlightsIndexRoute
  '/admin/flights/new': typeof AdminAdminFlightsNewRoute
  '/admin/flights/': typeof AdminAdminFlightsIndexRoute
  '/admin/flights/$flightId/edit': typeof AdminAdminFlightsFlightIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/manage': typeof PublicManageRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/flights/$flightId': typeof PublicFlightsFlightIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/flights': typeof PublicFlightsIndexRoute
  '/admin/flights/new': typeof AdminAdminFlightsNewRoute
  '/admin/flights': typeof AdminAdminFlightsIndexRoute
  '/admin/flights/$flightId/edit': typeof AdminAdminFlightsFlightIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/manage': typeof PublicManageRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_public/flights/$flightId': typeof PublicFlightsFlightIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/flights/': typeof PublicFlightsIndexRoute
  '/_admin/admin/flights/new': typeof AdminAdminFlightsNewRoute
  '/_admin/admin/flights/': typeof AdminAdminFlightsIndexRoute
  '/_admin/admin/flights/$flightId/edit': typeof AdminAdminFlightsFlightIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manage'
    | '/admin/bookings'
    | '/flights/$flightId'
    | '/admin/'
    | '/flights/'
    | '/admin/flights/new'
    | '/admin/flights/'
    | '/admin/flights/$flightId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manage'
    | '/admin/bookings'
    | '/flights/$flightId'
    | '/admin'
    | '/flights'
    | '/admin/flights/new'
    | '/admin/flights'
    | '/admin/flights/$flightId/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/login'
    | '/_public/manage'
    | '/_public/'
    | '/_admin/admin/bookings'
    | '/_public/flights/$flightId'
    | '/_admin/admin/'
    | '/_public/flights/'
    | '/_admin/admin/flights/new'
    | '/_admin/admin/flights/'
    | '/_admin/admin/flights/$flightId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/manage': {
      id: '/_public/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof PublicManageRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/flights/': {
      id: '/_public/flights/'
      path: '/flights'
      fullPath: '/flights/'
      preLoaderRoute: typeof PublicFlightsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/flights/$flightId': {
      id: '/_public/flights/$flightId'
      path: '/flights/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof PublicFlightsFlightIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/flights/': {
      id: '/_admin/admin/flights/'
      path: '/admin/flights'
      fullPath: '/admin/flights/'
      preLoaderRoute: typeof AdminAdminFlightsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/flights/new': {
      id: '/_admin/admin/flights/new'
      path: '/admin/flights/new'
      fullPath: '/admin/flights/new'
      preLoaderRoute: typeof AdminAdminFlightsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/flights/$flightId/edit': {
      id: '/_admin/admin/flights/$flightId/edit'
      path: '/admin/flights/$flightId/edit'
      fullPath: '/admin/flights/$flightId/edit'
      preLoaderRoute: typeof AdminAdminFlightsFlightIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminFlightsNewRoute: typeof AdminAdminFlightsNewRoute
  AdminAdminFlightsIndexRoute: typeof AdminAdminFlightsIndexRoute
  AdminAdminFlightsFlightIdEditRoute: typeof AdminAdminFlightsFlightIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminFlightsNewRoute: AdminAdminFlightsNewRoute,
  AdminAdminFlightsIndexRoute: AdminAdminFlightsIndexRoute,
  AdminAdminFlightsFlightIdEditRoute: AdminAdminFlightsFlightIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicManageRoute: typeof PublicManageRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicFlightsFlightIdRoute: typeof PublicFlightsFlightIdRoute
  PublicFlightsIndexRoute: typeof PublicFlightsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicManageRoute: PublicManageRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicFlightsFlightIdRoute: PublicFlightsFlightIdRoute,
  PublicFlightsIndexRoute: PublicFlightsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
